#!/bin/bash

orig_dir=$(pwd)
source ~/path/to/your/venvs/qemyenv/bin/activate # change to your path
cd ~/path/to/project/root/qemy # change to your path
python -m frontend.cli
deactivate 
cd "$orig_dir"
