#!/bin/bash

orig_dir=$(pwd)
source ~/path/to/your/venvs/qemyenv/bin/activate # change to your path
cd ~/path/to/projectroot/qemy # change to your path
python -m qemy.cli_main
deactivate 
cd "$orig_dir"
