# Qemy CLI colors
# https://rich.readthedocs.io/en/stable/appendix/colors.html

# Theme:
info = "magenta"
data = "green"
warning = "bold red"
title = "bold magenta underline"

# Tables:
table_border = "magenta"
table_row_style = ["dim", ""]
table_value_col = "green"
table_value_col_header = "bold green"
table_default_col = "magenta"
table_default_col_header = "bold magenta"

# Panels:
panel_text = "bold magenta"
panel_border = "magenta"

# Miscellaneous:
load_spinner = "magenta"

