# Qemy CLI colors
# https://rich.readthedocs.io/en/stable/appendix/colors.html

[theme]
info = "magenta"
data = "green"
warning = "bold red"
title = "bold magenta underline"

[table]
border = "magenta"
row_style = ["dim", ""]
value_col = "green"
value_col_header = "bold green"
default_col = "magenta"
default_col_header = "bold magenta"

[panel]
text = "bold magenta"
border = "magenta"

[misc]
load_spinner = "magenta"

